name: Build packages

on:
  pull_request:
    branches:
      - master
    paths:
      - 'main/**'
      - 'contrib/**'
      - 'user/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[ci skip]') && !contains(github.event.pull_request.body, '[ci skip]')"

    env:
      update_check: |-
        ${{
          ( !contains(github.event.pull_request.title, '[update skip]')
          && !contains(github.event.pull_request.body, '[update skip]') )
          && '--update-check'
          || ''
        }}

    steps:
      - name: env
        run: |
          env
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends ca-certificates python3.11 openssl git bubblewrap wget

      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Cache cbuild data
        id: cache-cbuild
        uses: actions/cache@v4
        env:
          cache-name: cbuild-ci-cache
        with:
          save-always: true
          path: |
            ./cbuild_cache
            ./sources
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Set up cbuild configuration
        run: sh .ci/setup-cbuild.sh

      - name: Cycle check
        run: env PYTHONUNBUFFERED=1 python3.11 cbuild cycle-check

      - name: Symlink check
        run: env PYTHONUNBUFFERED=1 python3.11 cbuild relink-subpkgs && git diff --exit-code

      - name: Build and test packages
        run: env PYTHONUNBUFFERED=1 python3.11 cbuild -W ${{ env.update_check }} -t bulk-pkg 'git:master..+!\[ci skip\]'
